# Generated by Django 5.1.1 on 2025-03-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre_completo', models.CharField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('f_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, default='', null=True, upload_to='fotos/')),
                ('tipoUsuario', models.CharField(choices=[('A', 'Admin'), ('B', 'Barbero'), ('C', 'Cliente')], default='C', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='ziara_app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Barberos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_trabajo', models.TextField()),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barberos_creados', to='ziara_app.usuarios')),
                ('usuario_barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberos', to='ziara_app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='ziara_app.usuarios')),
            ],
        ),
    ]
