# Generated by Django 4.2.11 on 2025-03-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/predeterminado.png', null=True, upload_to='fotos/'),
        ),
    ]
