# Generated by Django 4.2.11 on 2025-03-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0002_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='token_recuperar_clave',
            field=models.CharField(default='', max_length=6),
        ),
    ]
