# Generated by Django 5.1.1 on 2025-03-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0003_usuarios_token_recuperar_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
