# Generated by Django 5.1.1 on 2025-03-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0004_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
    ]
