# Generated by Django 4.2.11 on 2025-03-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0006_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberos',
            name='horario_trabajo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
