# Generated by Django 5.1.1 on 2025-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0007_alter_barberos_horario_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberos',
            name='experiencia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
