# Generated by Django 5.1.1 on 2025-03-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0009_alter_barberos_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberos',
            name='experiencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
