# Generated by Django 5.1.1 on 2025-03-22 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0010_alter_barberos_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Programada'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], max_length=4)),
                ('barbero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_barbero', to='ziara_app.barberos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_cliente', to='ziara_app.clientes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_servicio', to='ziara_app.servicios')),
            ],
        ),
    ]
