# Generated by Django 5.1.1 on 2025-03-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0011_servicios_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.FloatField(),
        ),
    ]
