# Generated by Django 5.1.1 on 2025-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0013_servicios_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='categoria',
            field=models.CharField(choices=[('B', 'Barba'), ('C', 'Cabello'), ('S', 'Spa')], default='', max_length=1),
        ),
    ]
