# Generated by Django 5.1.1 on 2025-03-25 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0014_alter_servicios_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
