# Generated by Django 5.1.1 on 2025-03-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0015_citas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='servicio',
        ),
        migrations.AddField(
            model_name='citas',
            name='servicio',
            field=models.ManyToManyField(related_name='cita_servicio', to='ziara_app.servicios'),
        ),
    ]
