# Generated by Django 5.1.1 on 2025-03-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0016_remove_citas_servicio_citas_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='servicio',
        ),
        migrations.AddField(
            model_name='citas',
            name='servicio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cita_servicio', to='ziara_app.servicios'),
            preserve_default=False,
        ),
    ]
