# Generated by Django 5.1.1 on 2025-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0017_remove_citas_servicio_citas_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Programada'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], max_length=3),
        ),
    ]
