# Generated by Django 5.1.1 on 2025-03-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0019_remove_citas_servicio_alter_servicios_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ziara_app.citas')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_servicio', to='ziara_app.servicios')),
            ],
        ),
    ]
