# Generated by Django 5.1.1 on 2025-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0020_citaservicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
