# Generated by Django 5.1.1 on 2025-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0021_alter_servicios_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
