# Generated by Django 5.1.1 on 2025-03-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0023_alter_servicios_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
