# Generated by Django 5.1.1 on 2025-04-01 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0024_servicios_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('categoria', models.CharField(choices=[('B', 'Barba'), ('C', 'Cabello'), ('R', 'Rostro')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_productos', to='ziara_app.productos')),
            ],
        ),
    ]
