# Generated by Django 5.1.1 on 2025-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0025_productos_inventarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='img_pixaby',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='img_pixaby',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='duracion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
