# Generated by Django 5.1.1 on 2025-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0026_productos_img_pixaby_servicios_img_pixaby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='img_pixaby',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
