# Generated by Django 5.1.1 on 2025-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0027_alter_servicios_img_pixaby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='img_pixaby',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
