# Generated by Django 5.1.1 on 2025-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0028_alter_servicios_img_pixaby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='img_pixaby',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='img_pixaby',
        ),
        migrations.AddField(
            model_name='productos',
            name='img_pixabay_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='img_pixabay_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
