# Generated by Django 5.1.1 on 2025-04-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0029_remove_productos_img_pixaby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='img_pixabay_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='img_pixabay_url',
            new_name='img_url',
        ),
    ]
