# Generated by Django 5.1.1 on 2025-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0030_rename_img_pixabay_url_productos_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
