# Generated by Django 5.1.1 on 2025-04-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0031_productos_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='referencia',
        ),
    ]
