# Generated by Django 4.2.11 on 2025-04-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0033_alter_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('B', 'Barba'), ('C', 'Cabello'), ('R', 'Rostro'), ('N', 'Natural'), ('P', 'Cuerpo')], default='', max_length=1),
        ),
    ]
