# Generated by Django 4.2.11 on 2025-04-08 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0036_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/predeterminado.png', null=True, upload_to='fotos/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
