# Generated by Django 5.1.1 on 2025-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0038_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/predeterminado.png', null=True, upload_to='fotos/'),
        ),
    ]
