# Generated by Django 4.2.11 on 2025-05-07 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0039_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/predeterminado.png', null=True, upload_to='fotos/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
