# Generated by Django 4.2.11 on 2025-05-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0040_usuarios_estado_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default='Activo', max_length=15),
        ),
    ]
