# Generated by Django 5.1.1 on 2025-05-08 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0041_alter_usuarios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
