# Generated by Django 5.1.1 on 2025-05-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0043_pagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='productos_comprados',
        ),
        migrations.CreateModel(
            name='ProductosComprados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_comprados', to='ziara_app.pagos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziara_app.productos')),
            ],
        ),
    ]
