# Generated by Django 5.1.1 on 2025-05-11 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziara_app', '0044_remove_pagos_productos_comprados_productoscomprados'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberos',
            name='hora_final',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='barberos',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='barberos',
            name='horario_trabajo',
            field=models.CharField(choices=[('semana', 'Lunes a Jueves'), ('fin_semana', 'Viernes a Domingo')], default='', max_length=100),
        ),
    ]
